name: datadog_flutter_plugin
description: Flutter bindings and tools for utilizing Datadog Mobile SDks
version: 2.4.0
repository: https://github.com/DataDog/dd-sdk-flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.7.0
  uuid: ^4.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0"
  mocktail: ^0.3.0
  json_serializable: ^6.7.0
  build_runner: ^2.1.11
  datadog_common_test:
    path: ../datadog_common_test

flutter:
  plugin:
    platforms:
      android:
        package: com.datadoghq.flutter
        pluginClass: DatadogSdkPlugin
      ios:
        pluginClass: DatadogSdkPlugin
      web:
        pluginClass: DatadogSdkWeb
        fileName: datadog_flutter_plugin_web.dart
