name: datadog_grpc_interceptor
description: A plugin for use with the DatadogSdk, used to track performance of gRPC and enable Datadog Distributed Tracing.
version: 1.2.0
homepage: http://datadoghq.com
repository: https://github.com/DataDog/dd-sdk-flutter

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  datadog_flutter_plugin: ^2.7.0
  grpc: ^3.0.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  protobuf: ^2.1.0
  datadog_common_test:
    path: ../datadog_common_test

flutter:
