name: releaser
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  args: ^2.3.0
  logging: ^1.0.2
  path: ^1.8.0
  git: ^2.3.0
  github: ^9.5.0
  version: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
