name: e2e_generator
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.1 <4.0.0'

dependencies:
  args: ^2.3.0
  logging: ^1.0.2
  path: ^1.8.0
  analyzer: ^3.2.0
  collection: ^1.15.0
  dart_style: ^2.2.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
