name: datadog_tracking_http_client
description: A wrapping implementation of HttpClient for tracking resources with Datadog
version: 1.0.1-beta.1
repository: https://github.com/DataDog/dd-sdk-flutter
homepage: https://datadoghq.com


environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  datadog_flutter_plugin: ^1.0.0-beta.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0

flutter:
