name: ci_helpers
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  http: ^1.2.1
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0  
